sudo: required
services:
  - docker

before_install:
  - docker build -t rahadyan/kodekurawal-api-test -f ./Dockerfile.dev .

script:
  - docker run -e PORT=$PORT -e DB_HOST=$DB_HOST -e MODE=$MODE rahadyan/kodekurawal-api-test npm test

after_success:
  - docker build -t rahadyan/kodekurawal-api .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rahadyan/kodekurawal-api

branches:
  only:
    - master