version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - ./data/db/
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env

