version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db/
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:4000"
    volumes:
      - ./usr/src/app/node_modules
      - ./src:/usr/src/app/src
    env_file:
      - .env

