import './achievement/detail/DetailAchievement'
import './player/achievement/PlayerAchievement'
import './avatar/Avatar'
import './achievement/Achievement'
import './badge/Badge'
import './course/stage/score/Score'
import './course/stage/mission/Mission'
import './course/stage/mission/testcase/TestCaseMission'
import './course/stage/Stage'
import './course/Course'
import './testcase/TestCase'
import './user/User'
import './player/Player'

import { merge } from 'lodash'
import achievement from './achievement/resolvers'
import avatar from './avatar/resolvers'
import badge from './badge/resolvers'
import course from './course/resolvers'
import player from './player/resolvers'
import testcase from './testcase/resolvers'
import user from './user/resolvers'

export default merge( achievement, avatar, badge, course,player, testcase, user)
